version: '3.9'

services:
  auth-service:
    build: ./auth-service
    ports:
      - "5005:5005"
    depends_on:
      - transaction-service

  transaction-service:
    build: ./transaction-service
    ports:
      - "5006:5006"
