version: '3.9'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: bank_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  auth-service:
    build: ./auth_service
    ports:
      - "5005:5005"
    environment:
      DB_HOST: db
      DB_NAME: bank_db
      DB_USER: user
      DB_PASS: password
    depends_on:
      - db
  transaction-service:
    build: ./transaction_service
    ports:
      - "5006:5006"
    environment:
      DB_HOST: db
      DB_NAME: bank_db
      DB_USER: user
      DB_PASS: password
    depends_on:
      - db

volumes:
  db_data:
  
